---
title: "usethis hist"
format: html
editor: visual
knitr: 
  opts_chunk: 
    eval: false
---

# Initial Setup

```{r}
renv::install("usethis")
```

## Description

```{r}
desc::desc_set_authors(
  person(
    given = "Josef",
    family = "Fruehwald",
    email = "jofrhwld@gmail.com",
    role = "cre"
  )
)
```

```{r}
desc::desc_del("Author")
desc::desc_del("Maintainer")
```

```{r}
desc::desc_set(
  Title = "RStudio plugin to add code annotation"
)
```

```{r}
usethis::use_gpl3_license()
```

## Infra

```{r}
renv::install("roxygen2")
renv::install("here")
```

```{r}
fs::file_delete(here::here("NAMESPACE"))
```

## Addin register

```{r}
renv::install("readr")
```

```{r}
fs::dir_create(
  here::here(
    "inst",
    "rstudio"
  ),
  recurse = T
)

readr::write_lines(
  c(
    "Name: annotate code",
    "Description: Inserts code annotation on selected lines.",
    "Binding: codeannotate",
    "Interactive: false"
  ),
  file = here::here(
    "inst",
    "rstudio",
    "addins.dcf"
  )
)
```

## Code Setup

```{r}
fs::file_delete(
  here::here(
    "R",
    "hello.R"
  )
)

fs::file_touch(
  here::here(
    "R",
    "codeannotate.R"
  )
)

```

# Packages

```{r}
usethis::use_package("rstudioapi")
```
